error: apply to switch yaml parsing
Put the reviewed Error configs to the switch from_yaml_config.
Introduce the InvalidAddress variant in the ConfigError.

Signed-off-by: Paul Wekesa <paul1tw1@gmail.com>