error: Router::from_yaml_config to thiserror
As refactor of the error handling continues, we move from_yaml_config in
Router to point to the thiserror enum.

Signed-off-by: Paul Wekesa <paul1tw1@gmail.com>