error: Introduce error handling
- introduce error.rs and Error enums
- remove redundanct impl Interface's

Signed-off-by: Paul Wekesa <paul1tw1@gmail.com>